# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           ./docs
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

exclude:
  - "jade"
  - "vendor"

# Custom vars
current_version:  2.0.0
repo:             https://github.com/aozora/bootplus

download:
  source:         https://github.com/aozora/bootplus/archive/v2.0.0.zip
  dist:           https://github.com/aozora/bootplus/releases/download/v2.0.0/bootplus-2.0.0-dist.zip

blog:             http://aozora.github.com/bootplus/

